import './globals.css'
import { Navbar } from '@/components'

export const metadata = {
  title: 'NextJS | Apple Store',
  description: 'Generated by erdemarslan',
}

export default function RootLayout({ children })
{
  return (
    <html lang="en">
      <body className={`bg-default-bg `}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
